services:
  wall_e_ros2:
    build:
      context: .
      dockerfile: Dockerfile
    image: wall_e_ros2:latest
    container_name: wall_e_ros2
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - /home/nixjetson/WALL_E_ROS2:/ros2_ws

    working_dir: /ros2_ws
    depends_on:
      - ollama
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/rfcomm0:/dev/rfcomm0

  ollama:
    image: ollama/ollama
    container_name: ollama
    network_mode: host
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

volumes:
  ollama_models:
