services:
  socketserver:
    build:
      context: ..  # This is the root (WebSocketGateway/)
      dockerfile: WebSocketGateway/WebSocketGateway/Dockerfile # Path from the new root
    image: "socketserver"
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build: .
    image: ${JUPYTER_LAB_CONTAINER}
    container_name: jupyter-lab-host
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8888:8888"
    volumes:
      - ./projects:/app/projects
    environment:
      - JUPYTER_TOKEN=${SECRET_PASSWORD}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all#compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities: [gpu]

  ollama:
    image: ollama/ollama
    network_mode: "host"
    container_name: ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/lib/ollama:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:11434"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities: [gpu]

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${SECRET_TOKEN}
