using System.Net;
using System.Net.Sockets;
using System.Text;

float simulatedEulerY = 0;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

var summaries = new[]
{
    "Freezing",
    "Bracing",
    "Chilly",
    "Cool",
    "Mild",
    "Warm",
    "Balmy",
    "Hot",
    "Sweltering",
    "Scorching",
};

app.MapGet(
        "/weatherforecast",
        () =>
        {
            var forecast = Enumerable
                .Range(1, 5)
                .Select(index => new WeatherForecast(
                    DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                    Random.Shared.Next(-20, 55),
                    summaries[Random.Shared.Next(summaries.Length)]
                ))
                .ToArray();
            return forecast;
        }
    )
    .WithName("GetWeatherForecast")
    .WithOpenApi();
app.MapGet(
        "/test-tank",
        () =>
        {
            // 1. Create a new instance of your struct
            TankStatus myTank = new TankStatus();

            // 2. Pass it to the C library by reference to initialize it
            TankStatusNative.constructTankStatus(ref myTank);

            // 3. Create a byte array for your buffer (your C header says 8 bytes of data,
            //    but the struct is technically 9 bytes + padding. Let's make it 10 to be safe)
            byte[] buffer = new byte[10];

            // 4. Call the C function to serialize the struct into the buffer
            TankStatusNative.makeByteTankStatus(buffer, buffer.Length, ref myTank);

            // Now 'buffer' contains the raw bytes generated by your C library!
            return Results.Ok(new { Message = "Success", Buffer = buffer });
        }
    )
    .WithName("GetTestTank")
    .WithOpenApi();

app.MapPost(
    "/update-eulerY",
    async (float eulerY) =>
    {
        // This constructor arbitrarily assigns the local port number.
        UdpClient udpClient = new UdpClient();
        udpClient.Connect("127.0.0.1", 8881);

        // Sends a message to the host to which you have connected.
        Byte[] sendBytes = Encoding.ASCII.GetBytes("Is anybody there?");

        udpClient.Send(sendBytes, sendBytes.Length);

        udpClient.Close();
    }
);

app.MapGet(
    "/dump-test",
    async () =>
    {
        string targetIp = "10.98.48.5";
        int targetPort = 8881;

        // Initialize the UDP client
        using UdpClient udpClient = new UdpClient();

        Console.WriteLine($"Starting UDP dump to {targetIp}:{targetPort}...");
        Console.WriteLine("Press Ctrl+C to stop.");

        try
        {
            // 1. Create a fresh TankStatus struct
            TankStatus ts = new TankStatus();

            // Call the C constructor to set any defaults
            TankStatusNative.constructTankStatus(ref ts);

            // 2. Simulate changing data
            ts.driveLeft = 127; // Half speed
            ts.driveRight = 255; // Full speed
            ts.eulerX = TankStatusNative.getEncodedFloatToShort(simulatedEulerY);
            ts.eulerY = TankStatusNative.getEncodedFloatToShort(90);
            ts.eulerZ = TankStatusNative.getEncodedFloatToShort(-45);
            ts.changeFlag = 1;

            // 3. Prepare the byte buffer (8 bytes)
            byte[] byteData = new byte[TankStatusNative.get_tankstatus_packet_length()];

            // 4. Let the C library pack the struct into the byte array!
            TankStatusNative.makeByteTankStatus(byteData, byteData.Length, ref ts);

            // 5. Send the full packet to Godot
            await udpClient.SendAsync(byteData, byteData.Length, targetIp, targetPort);

            // Print the struct data and the raw hex bytes for debugging
            string hexString = BitConverter.ToString(byteData).Replace("-", "");
            Console.WriteLine($"Sent EulerX: {ts.eulerX, 4} | Hex: {hexString}");

            // Increment the simulated value and wrap around at 360 degrees
            simulatedEulerY += 10;
            if (simulatedEulerY > 360)
            {
                simulatedEulerY = 0;
            }

            // Wait 500ms before sending the next packet
            await Task.Delay(500);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"\nError during UDP send: {ex.Message}");
        }
    }
);

app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
