using System.Net;
using System.Net.Sockets;
using System.Text;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.Net.Http.Headers;

float simulatedEulerY = 0;

TankStatus tankBotStatus = new TankStatus();
TankStatusNative.constructTankStatus(ref tankBotStatus);

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddAuthentication();

var MyAllowSpecificOrigins = "_myAllowSpecificOrigins";

// Or, for development/testing, you can allow any origin (use with caution in production)
builder.Services.AddCors(options =>
{
    options.AddPolicy(
        name: MyAllowSpecificOrigins,
        builder =>
        {
            builder
                // .WithOrigins("https://partywanted.digi.wifi",
                //                                                                           "http://partywanted.digi.wifi")
                .AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader();
            //.AllowCredentials();
        }
    );
});
builder.Services.AddResponseCompression(options =>
{
    options.EnableForHttps = true;
});

var app = builder.Build();

//app.UseHttpsRedirection();

var provider = new FileExtensionContentTypeProvider();
provider.Mappings[".pck"] = "application/octet-stream";
provider.Mappings[".wasm"] = "application/wasm";

app.UseStaticFiles(new StaticFileOptions { ContentTypeProvider = provider });

app.UseCors("_myAllowSpecificOrigins");

provider.Mappings[".dll"] = "application/octet-stream";
provider.Mappings[".pdb"] = "application/octet-stream";

app.UseStaticFiles(
    new StaticFileOptions
    {
        ContentTypeProvider = provider,

        // Optional: Add aggressive caching for game files to speed up repeat visits
        OnPrepareResponse = ctx =>
        {
            var headers = ctx.Context.Response.GetTypedHeaders();
            headers.CacheControl = new CacheControlHeaderValue
            {
                Public = true,
                MaxAge = TimeSpan.FromDays(30),
            };
        },
    }
);
app.Use(
    async (context, next) =>
    {
        context.Response.Headers.Append("Cross-Origin-Opener-Policy", "same-origin");
        context.Response.Headers.Append("Cross-Origin-Embedder-Policy", "require-corp");

        // Optional but recommended: Prevent browsers from trying to guess file types
        context.Response.Headers.Append("X-Content-Type-Options", "nosniff");

        await next();
    }
);

app.MapGet(
        "/test-tank",
        () =>
        {
            // 1. Create a new instance of your struct
            TankStatus myTank = new TankStatus();

            // 2. Pass it to the C library by reference to initialize it
            TankStatusNative.constructTankStatus(ref myTank);

            // 3. Create a byte array for your buffer (your C header says 8 bytes of data,
            //    but the struct is technically 9 bytes + padding. Let's make it 10 to be safe)
            byte[] buffer = new byte[10];

            // 4. Call the C function to serialize the struct into the buffer
            TankStatusNative.makeByteTankStatus(buffer, buffer.Length, ref myTank);

            // Now 'buffer' contains the raw bytes generated by your C library!
            return Results.Ok(new { Message = "Success", Buffer = buffer });
        }
    )
    .WithName("GetTestTank")
    .WithOpenApi();

app.MapPost(
    "/update-eulerY",
    async (float eulerY) =>
    {
        // This constructor arbitrarily assigns the local port number.
        UdpClient udpClient = new UdpClient();
        udpClient.Connect("127.0.0.1", 8881);

        // Sends a message to the host to which you have connected.
        Byte[] sendBytes = Encoding.ASCII.GetBytes("Is anybody there?");

        udpClient.Send(sendBytes, sendBytes.Length);

        udpClient.Close();
    }
);

app.MapGet(
    "/dump-test",
    async () =>
    {
        string targetIp = "10.98.48.5";
        int targetPort = 8881;

        // Initialize the UDP client
        using UdpClient udpClient = new UdpClient();

        Console.WriteLine($"Starting UDP dump to {targetIp}:{targetPort}...");
        Console.WriteLine("Press Ctrl+C to stop.");

        try
        {
            // 1. Create a fresh TankStatus struct
            TankStatus ts = new TankStatus();

            // Call the C constructor to set any defaults
            TankStatusNative.constructTankStatus(ref ts);

            // 2. Simulate changing data
            ts.driveLeft = 127; // Half speed
            ts.driveRight = 255; // Full speed

            ts.eulerX = TankStatusNative.getEncodedFloatToShort(simulatedEulerY);
            ts.eulerY = TankStatusNative.getEncodedFloatToShort(90.0f);
            ts.eulerZ = TankStatusNative.getEncodedFloatToShort(-45.0f);
            ts.changeFlag = 1;

            // 3. Prepare the byte buffer (8 bytes)
            byte[] byteData = new byte[TankStatusNative.get_tankstatus_packet_length()];

            // 4. Let the C library pack the struct into the byte array!
            TankStatusNative.makeByteTankStatus(byteData, byteData.Length, ref ts);

            // 5. Send the full packet to Godot
            await udpClient.SendAsync(byteData, byteData.Length, targetIp, targetPort);

            // Print the struct data and the raw hex bytes for debugging
            string hexString = BitConverter.ToString(byteData).Replace("-", "");
            Console.WriteLine($"Sent EulerX: {ts.eulerX,4} | Hex: {hexString}");

            // Increment the simulated value and wrap around at 360 degrees
            simulatedEulerY += 10;
            if (simulatedEulerY > 360)
            {
                simulatedEulerY = 0;
            }

            // Wait 500ms before sending the next packet
            await Task.Delay(500);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"\nError during UDP send: {ex.Message}");
        }
    }
);
//app.UseHttpsRedirection();
//
//


app.MapPost("/api/setTankStatus", async (HttpContext context) =>
{
    using var ms = new MemoryStream();
    await context.Request.Body.CopyToAsync(ms);
    byte[] tsData = ms.ToArray();

    //    Console.WriteLine($"TankStatusNative.PacketLength{TankStatusNative.PacketLength}");

    if (tsData.Length >= TankStatusNative.PacketLength)
    {
        // Update the global state
        TankStatusNative.readByteTankStatus(tsData, tsData.Length, ref tankBotStatus);
        return Results.Ok();
    }
    return Results.BadRequest("Packet too short");
});


app.MapGet("/api/getTankStatusBytes", ()
    =>
    {
        byte[] tsBytesBuffer = Array.Empty<byte>();
        TankStatusNative.makeByteTankStatus(tsBytesBuffer, TankStatusNative.PacketLength, ref tankBotStatus);
        return tsBytesBuffer;
    });


app.MapGet("/api/getTankStatusJson", () =>
{
    return Results.Ok(new
    {
        left = tankBotStatus.driveLeft,
        right = tankBotStatus.driveRight,
        x = TankStatusNative.getDecodedShortToFloat(tankBotStatus.eulerX),
        y = TankStatusNative.getDecodedShortToFloat(tankBotStatus.eulerY),
        z = TankStatusNative.getDecodedShortToFloat(tankBotStatus.eulerZ),
        flag = tankBotStatus.changeFlag
    });
});

app.MapGet("/api/getTankStatusOneTime", () =>
{
    // Decode the shorts into readable floats using your helper
    float x = TankStatusNative.getDecodedShortToFloat(tankBotStatus.eulerX);
    float y = TankStatusNative.getDecodedShortToFloat(tankBotStatus.eulerY);
    float z = TankStatusNative.getDecodedShortToFloat(tankBotStatus.eulerZ);

    // Build the HTML string
    string htmlContent = $@"
    <html>
        <body style='font-family: monospace; background-color: #121212; color: #00ff00; padding: 20px;'>
            <h2>TankBot System Status</h2>
            <hr/>
            <p><b>Motor Left:</b>  {tankBotStatus.driveLeft}</p>
            <p><b>Motor Right:</b> {tankBotStatus.driveRight}</p>
            <br/>
            <p><b>Euler X:</b>     {x:F2}</p>
            <p><b>Euler Y:</b>     {y:F2}</p>
            <p><b>Euler Z:</b>     {z:F2}</p>
            <hr/>
            <p><b>Change Flag:</b> {tankBotStatus.changeFlag}</p>
            <p><b>Timestamp:</b>   {DateTime.Now:HH:mm:ss}</p>
        </body>
    </html>";

    // Returns the string with the correct MIME type so the browser renders it
    return Results.Content(htmlContent, "text/html");
});

app.MapGet("/api/getTankStatus", () =>
{
    string htmlContent = $@"
    <html>
        <head>
            <title>TANKBOT Live Telemetry</title>
            <style>
                body {{ font-family: 'Courier New', monospace; background: #0a0a0a; color: #33ff33; padding: 20px; }}
                .stat-box {{ border: 1px solid #33ff33; padding: 10px; margin: 10px 0; width: 300px; }}
                .val {{ color: white; font-weight: bold; }}
            </style>
        </head>
        <body>
            <h2>TANKBOT LIVE STATUS</h2>
            <div class='stat-box'>
                <div>LEFT MOTOR:  <span id='l' class='val'>--</span>/255</div>
                <div>RIGHT MOTOR: <span id='r' class='val'>--</span>/255</div>
            </div>
            <div class='stat-box'>
                <div>EULER X: <span id='ex' class='val'>--</span>deg</div>
                <div>EULER Y: <span id='ey' class='val'>--</span>deg</div>
                <div>EULER Z: <span id='ez' class='val'>--</span>deg</div>
            </div>

            <script>
                async function updateStatus() {{
                    try {{
                        const response = await fetch('/api/getTankStatusJson');
                        const data = await response.json();
                        
                        // Update the HTML elements by ID
                        document.getElementById('l').innerText = data.left;
                        document.getElementById('r').innerText = data.right;
                        document.getElementById('ex').innerText = data.x.toFixed(2);
                        document.getElementById('ey').innerText = data.y.toFixed(2);
                        document.getElementById('ez').innerText = data.z.toFixed(2);
                        document.getElementById('flag').innerText = data.flag;
                    }} catch (err) {{
                        console.error('Data link lost:', err);
                    }}
                }}

                // Run every 200 milliseconds
                setInterval(updateStatus, 200);
            </script>
        </body>
    </html>";

    return Results.Content(htmlContent, "text/html");
});

app.MapGet(
    "/webui",
    (IWebHostEnvironment env) =>
    {
        var indexPath = Path.Combine(env.WebRootPath, "webui_tankstatus.html");
        return Results.File(indexPath, "text/html");
    }
);
app.MapGet(
    "/drive",
    (IWebHostEnvironment env) =>
    {
        var indexPath = Path.Combine(env.WebRootPath, "drive.html");
        return Results.File(indexPath, "text/html");
    }
);

app.Run();
