var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

var summaries = new[]
{
    "Freezing",
    "Bracing",
    "Chilly",
    "Cool",
    "Mild",
    "Warm",
    "Balmy",
    "Hot",
    "Sweltering",
    "Scorching",
};

app.MapGet(
        "/weatherforecast",
        () =>
        {
            var forecast = Enumerable
                .Range(1, 5)
                .Select(index => new WeatherForecast(
                    DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                    Random.Shared.Next(-20, 55),
                    summaries[Random.Shared.Next(summaries.Length)]
                ))
                .ToArray();
            return forecast;
        }
    )
    .WithName("GetWeatherForecast")
    .WithOpenApi();
app.MapGet(
        "/test-tank",
        () =>
        {
            // 1. Create a new instance of your struct
            TankStatus myTank = new TankStatus();

            // 2. Pass it to the C library by reference to initialize it
            TankStatusNative.constructTankStatus(ref myTank);

            // 3. Create a byte array for your buffer (your C header says 8 bytes of data,
            //    but the struct is technically 9 bytes + padding. Let's make it 10 to be safe)
            byte[] buffer = new byte[10];

            // 4. Call the C function to serialize the struct into the buffer
            TankStatusNative.makeByteTankStatus(buffer, buffer.Length, ref myTank);

            // Now 'buffer' contains the raw bytes generated by your C library!
            return Results.Ok(new { Message = "Success", Buffer = buffer });
        }
    )
    .WithName("GetTestTank")
    .WithOpenApi();

app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
